### ISSUE TITLE
android 闪退

### ISSUE THREAD

**Issue by tinybearc** [sdkbox/sdkbox-sample-sdkboxplay#7]
### sdkboxplay 版本：2.2.3.1

真机上闪退

~~~
06-08 09:41:50.890: E/Trace(21462): error opening trace file: No such file or directory (2)
06-08 09:41:50.930: I/System.out(21462): Sending WAIT chunk
06-08 09:41:50.930: W/ActivityThread(21462): Application com.sdkbox.main is waiting for the debugger on port 8100...
06-08 09:41:51.130: I/dalvikvm(21462): Debugger is active
06-08 09:41:51.130: I/System.out(21462): Debugger has connected
06-08 09:41:51.140: I/System.out(21462): waiting for debugger to settle...
06-08 09:41:51.340: I/System.out(21462): waiting for debugger to settle...
06-08 09:41:51.540: I/System.out(21462): waiting for debugger to settle...
06-08 09:41:51.750: I/System.out(21462): waiting for debugger to settle...
06-08 09:41:51.950: I/System.out(21462): waiting for debugger to settle...
06-08 09:41:52.150: I/System.out(21462): waiting for debugger to settle...
06-08 09:41:52.350: I/System.out(21462): waiting for debugger to settle...
06-08 09:41:52.550: I/System.out(21462): waiting for debugger to settle...
06-08 09:41:52.750: I/System.out(21462): debugger has settled (1404)
06-08 09:41:53.010: V/Activity(21462): onCreate org.cocos2dx.cpp.AppActivity@419ca5d8: null
06-08 09:41:53.060: D/dalvikvm(21462): Trying to load lib /mnt/asec/com.sdkbox.main-1/lib/libcocos2dcpp.so 0x419ae680
06-08 09:41:54.980: D/dalvikvm(21462): Added shared lib /mnt/asec/com.sdkbox.main-1/lib/libcocos2dcpp.so 0x419ae680
06-08 09:41:54.980: D/JniHelper(21462): JniHelper::setJavaVM(0x40161b40), pthread_self() = 1075377712
06-08 09:41:54.980: D/main(21462): cocos_android_app_init
06-08 09:41:54.990: I/SDKBOX_CORE(21462): Sdkbox Droid starting.
06-08 09:41:54.990: I/SDKBOX_CORE(21462): Sdkbox got VM.
06-08 09:41:54.990: I/SDKBOX_CORE(21462): Sdkbox jni initialized.
06-08 09:41:54.990: D/SDKBOX_CORE(21462): Can't load tracking info: java.io.IOException: BufferedInputStream is closed
06-08 09:41:55.100: E/dalvikvm(21462): Could not find class 'android.os.UserManager', referenced from method com.google.android.gms.common.zze.zzan
06-08 09:41:55.100: W/dalvikvm(21462): VFY: unable to resolve check-cast 275 (Landroid/os/UserManager;) in Lcom/google/android/gms/common/zze;
06-08 09:41:55.100: D/dalvikvm(21462): VFY: replacing opcode 0x1f at 0x000c
06-08 09:41:55.100: I/dalvikvm(21462): Could not find method android.content.pm.PackageManager.getPackageInstaller, referenced from method com.google.android.gms.common.zze.zzk
06-08 09:41:55.100: W/dalvikvm(21462): VFY: unable to resolve virtual method 502: Landroid/content/pm/PackageManager;.getPackageInstaller ()Landroid/content/pm/PackageInstaller;
06-08 09:41:55.100: D/dalvikvm(21462): VFY: replacing opcode 0x6e at 0x000b
06-08 09:41:55.100: E/dalvikvm(21462): Could not find class 'android.app.AppOpsManager', referenced from method com.google.android.gms.internal.zzpv.zzg
06-08 09:41:55.100: W/dalvikvm(21462): VFY: unable to resolve check-cast 27 (Landroid/app/AppOpsManager;) in Lcom/google/android/gms/internal/zzpv;
06-08 09:41:55.100: D/dalvikvm(21462): VFY: replacing opcode 0x1f at 0x0010
06-08 09:41:55.120: V/GoogleSignatureVerifier(21462): com.google.android.gms signature not valid.  Found: 
06-08 09:41:55.120: V/GoogleSignatureVerifier(21462): MIIEQzCCAyugAwIBAgIJAMLgh0ZkSjCNMA0GCSqGSIb3DQEBBAUAMHQxCzAJBgNVBAYTAlVTMRMw
06-08 09:41:55.120: V/GoogleSignatureVerifier(21462): EQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQHEw1Nb3VudGFpbiBWaWV3MRQwEgYDVQQKEwtHb29n
06-08 09:41:55.120: V/GoogleSignatureVerifier(21462): bGUgSW5jLjEQMA4GA1UECxMHQW5kcm9pZDEQMA4GA1UEAxMHQW5kcm9pZDAeFw0wODA4MjEyMzEz
06-08 09:41:55.120: V/GoogleSignatureVerifier(21462): MzRaFw0zNjAxMDcyMzEzMzRaMHQxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYw
06-08 09:41:55.120: V/GoogleSignatureVerifier(21462): FAYDVQQHEw1Nb3VudGFpbiBWaWV3MRQwEgYDVQQKEwtHb29nbGUgSW5jLjEQMA4GA1UECxMHQW5k
06-08 09:41:55.120: V/GoogleSignatureVerifier(21462): cm9pZDEQMA4GA1UEAxMHQW5kcm9pZDCCASAwDQYJKoZIhvcNAQEBBQADggENADCCAQgCggEBAKtW
06-08 09:41:55.120: V/GoogleSignatureVerifier(21462): LgDYO6IIrgqWbxJOKdoR8qtW0I9Y4sypEwPpt1TTcvZApxsdyxMJZ2JORland2qSGT2y5b+3JKke
06-08 09:41:55.120: V/GoogleSignatureVerifier(21462): dxiLDmpHpDsz2WCbdxgxRczfey5YZnTJ4VZbH0xqWVW/8lGmPav5xVwnIiJS6HXk+BVKZF+JcWjA
06-08 09:41:55.120: V/GoogleSignatureVerifier(21462): sb/GEuq/eFdpuzSqeYTcfi6idkyugwfYwXFU1+5fZKUaRKYCwkkFQVfcAs1fXA5V+++FGfvjJ/Cx
06-08 09:41:55.120: V/GoogleSignatureVerifier(21462): URaSxaBvGdGDhfXE28LWuT9ozCl5xw4Yq5OGazvV24mZVSoOO0yZ31j7kYvtwYK6NeADwbSxDdJE
06-08 09:41:55.120: V/GoogleSignatureVerifier(21462): qO4k//0zOHKrUiGYXtqw/A0LFFtqoZKFjnkCAQOjgdkwgdYwHQYDVR0OBBYEFMd9jMIhF1Ylmn/T
06-08 09:41:55.120: V/GoogleSignatureVerifier(21462): gt9r45jk14alMIGmBgNVHSMEgZ4wgZuAFMd9jMIhF1Ylmn/Tgt9r45jk14aloXikdjB0MQswCQYD
06-08 09:41:55.120: V/GoogleSignatureVerifier(21462): VQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNTW91bnRhaW4gVmlldzEUMBIG
06-08 09:41:55.120: V/GoogleSignatureVerifier(21462): A1UEChMLR29vZ2xlIEluYy4xEDAOBgNVBAsTB0FuZHJvaWQxEDAOBgNVBAMTB0FuZHJvaWSCCQDC
06-08 09:41:55.120: V/GoogleSignatureVerifier(21462): 4IdGZEowjTAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBBAUAA4IBAQBt0lLO74UwLDYKqs6Tm8/y
06-08 09:41:55.120: V/GoogleSignatureVerifier(21462): zKkEu116FmH4rkaymUIE0P9KaMftGlMexFlaYjzmB2OxZyl6euNXEsQH8gjwyxCUKRJNexBiGcCE
06-08 09:41:55.120: V/GoogleSignatureVerifier(21462): yj6z+a1fuHHvkiaai+KL8W1EyNmgjmyy8AW7P+LLlkR+ho5zEHatRbM/YAnqGcFh5iZBqpknHf1S
06-08 09:41:55.120: V/GoogleSignatureVerifier(21462): KMXFh4dd239FJ1jWYfbMDMy3NS5CTMQ2XFI1MvcyUTdZPErjQfTbQe3aDQsQcafEQPD+nqActifK
06-08 09:41:55.120: V/GoogleSignatureVerifier(21462): Z0Np0IS9L9kR/wbNvyz6ENwPiTrjV2KRkEjH78ZMcUQXg0L3BYHJ3lc69Vs5Ddf9uUGGMYldX3Wf
06-08 09:41:55.120: V/GoogleSignatureVerifier(21462): MBEmh/9iFBDAaTCK
06-08 09:41:55.120: E/TrackingInfo(21462): reqAdvertisingIdentifier Exception:java.lang.IllegalStateException: The meta-data tag in your app's AndroidManifest.xml does not have the right value.  Expected 9080000 but found 8298000.  You must have the following declaration within the <application> element:     <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
06-08 09:41:55.480: D/dalvikvm(21462): GC_CONCURRENT freed 246K, 6% free 13442K/14279K, paused 16ms+3ms, total 73ms
06-08 09:41:55.480: D/dalvikvm(21462): WAIT_FOR_CONCURRENT_GC blocked 22ms
06-08 09:41:55.590: D/dalvikvm(21462): GC_CONCURRENT freed 527K, 9% free 13359K/14599K, paused 5ms+3ms, total 22ms
06-08 09:41:55.770: D/Cocos2dxActivity(21462): model=Coolpad 5951
06-08 09:41:55.770: D/Cocos2dxActivity(21462): product=Coolpad5951
06-08 09:41:55.770: D/Cocos2dxActivity(21462): isEmulator=false
06-08 09:41:55.820: D/Cocos2dxActivity(21462): onResume()
06-08 09:41:55.820: V/Activity(21462): onStart org.cocos2dx.cpp.AppActivity@419ca5d8
06-08 09:41:55.820: V/Activity(21462): onResume org.cocos2dx.cpp.AppActivity@419ca5d8
06-08 09:41:55.980: W/SurfaceView(21462): mSurface.isValid() is true
06-08 09:41:55.980: W/SurfaceView(21462): enter the mSurface
06-08 09:41:56.000: D/libEGL(21462): loaded /system/lib/egl/libEGL_adreno200.so
06-08 09:41:56.020: D/libEGL(21462): loaded /system/lib/egl/libGLESv1_CM_adreno200.so
06-08 09:41:56.020: W/SurfaceView(21462): mSurface.isValid() is true
06-08 09:41:56.030: D/libEGL(21462): loaded /system/lib/egl/libGLESv2_adreno200.so
06-08 09:41:56.030: I/Log_level_control(21462): YVV7
06-08 09:41:56.030: I/Adreno200-EGL(21462): <qeglDrvAPI_eglInitialize:299>: EGL 1.4 QUALCOMM build: Nondeterministic AU_msm8625_REFS/TAGS/JB_REL_RB5_QRD_D20130303_CL3285357_release_AU (CL3285357)
06-08 09:41:56.030: I/Adreno200-EGL(21462): Build Date: 03/04/13 Mon
06-08 09:41:56.030: I/Adreno200-EGL(21462): Local Branch: 
06-08 09:41:56.030: I/Adreno200-EGL(21462): Remote Branch: m/refs/tags/jb_rel_rb5_qrd_D20130303
06-08 09:41:56.030: I/Adreno200-EGL(21462): Local Patches: NONE
06-08 09:41:56.030: I/Adreno200-EGL(21462): Reconstruct Branch: NOTHING
06-08 09:41:56.120: D/Cocos2dxActivity(21462): onWindowFocusChanged() hasFocus=true
06-08 09:41:56.240: D/cocos2d-x debug info(21462): {
06-08 09:41:56.240: D/cocos2d-x debug info(21462): 	gl.supports_vertex_array_object: true
06-08 09:41:56.240: D/cocos2d-x debug info(21462): 	gl.supports_BGRA8888: false
06-08 09:41:56.240: D/cocos2d-x debug info(21462): 	gl.supports_ATITC: true
06-08 09:41:56.240: D/cocos2d-x debug info(21462): 	gl.supports_S3TC: false
06-08 09:41:56.240: D/cocos2d-x debug info(21462): 	cocos2d.x.version: cocos2d-x-3.9
06-08 09:41:56.240: D/cocos2d-x debug info(21462): 	gl.supports_discard_framebuffer: false
06-08 09:41:56.240: D/cocos2d-x debug info(21462): 	cocos2d.x.compiled_with_profiler: false
06-08 09:41:56.240: D/cocos2d-x debug info(21462): 	gl.supports_PVRTC: false
06-08 09:41:56.240: D/cocos2d-x debug info(21462): 	cocos2d.x.build_type: DEBUG
06-08 09:41:56.240: D/cocos2d-x debug info(21462): 	gl.renderer: Adreno (TM) 203
06-08 09:41:56.240: D/cocos2d-x debug info(21462): 	gl.supports_ETC1: true
06-08 09:41:56.240: D/cocos2d-x debug info(21462): 	cocos2d.x.compiled_with_gl_state_cache: true
06-08 09:41:56.240: D/cocos2d-x debug info(21462): 	gl.version: OpenGL ES 2.0 V@6.0 AU@ (CL@3285357)
06-08 09:41:56.240: D/cocos2d-x debug info(21462): 	gl.supports_NPOT: true
06-08 09:41:56.240: D/cocos2d-x debug info(21462): 	gl.max_texture_units: 20
06-08 09:41:56.240: D/cocos2d-x debug info(21462): 	gl.vendor: Qualcomm
06-08 09:41:56.240: D/cocos2d-x debug info(21462): 	gl.max_texture_size: 4096
06-08 09:41:56.240: D/cocos2d-x debug info(21462): }
06-08 09:41:56.310: I/SDKBOX_CORE(21462): Initialization request for plugin: 'com/sdkbox/plugin/PluginSdkboxPlay'
06-08 09:41:56.420: I/dalvikvm(21462): Could not find method android.view.View.getDisplay, referenced from method com.google.android.gms.games.internal.PopupManager$PopupManagerHCMR1.zzt
06-08 09:41:56.420: W/dalvikvm(21462): VFY: unable to resolve virtual method 9481: Landroid/view/View;.getDisplay ()Landroid/view/Display;
06-08 09:41:56.420: D/dalvikvm(21462): VFY: replacing opcode 0x6e at 0x0009
06-08 09:41:56.430: W/PopupManager(21462): You have not specified a View to use as content view for popups. Falling back to the Activity content view. Note that this may not work as expected in multi-screen environments
06-08 09:41:56.480: D/dalvikvm(21462): GC_CONCURRENT freed 169K, 7% free 13588K/14599K, paused 12ms+2ms, total 29ms
06-08 09:41:56.490: D/AndroidRuntime(21462): Shutting down VM
06-08 09:41:56.490: W/dalvikvm(21462): threadid=1: thread exiting with uncaught exception (group=0x40c3e588)
06-08 09:41:56.510: E/AndroidRuntime(21462): FATAL EXCEPTION: main
06-08 09:41:56.510: E/AndroidRuntime(21462): java.lang.IllegalStateException: The meta-data tag in your app's AndroidManifest.xml does not have the right value.  Expected 9080000 but found 8298000.  You must have the following declaration within the <application> element:     <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
06-08 09:41:56.510: E/AndroidRuntime(21462): 	at com.google.android.gms.common.zze.zzaj(Unknown Source)
06-08 09:41:56.510: E/AndroidRuntime(21462): 	at com.google.android.gms.common.zze.isGooglePlayServicesAvailable(Unknown Source)
06-08 09:41:56.510: E/AndroidRuntime(21462): 	at com.google.android.gms.common.zzc.isGooglePlayServicesAvailable(Unknown Source)
06-08 09:41:56.510: E/AndroidRuntime(21462): 	at com.google.android.gms.common.GoogleApiAvailability.isGooglePlayServicesAvailable(Unknown Source)
06-08 09:41:56.510: E/AndroidRuntime(21462): 	at com.google.android.gms.internal.zzod$zzb.zzrX(Unknown Source)
06-08 09:41:56.510: E/AndroidRuntime(21462): 	at com.google.android.gms.internal.zzod$zzf.run(Unknown Source)
06-08 09:41:56.510: E/AndroidRuntime(21462): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
06-08 09:41:56.510: E/AndroidRuntime(21462): 	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
06-08 09:41:56.510: E/AndroidRuntime(21462): 	at java.util.concurrent.FutureTask.run(FutureTask.java:137)
06-08 09:41:56.510: E/AndroidRuntime(21462): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
06-08 09:41:56.510: E/AndroidRuntime(21462): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
06-08 09:41:56.510: E/AndroidRuntime(21462): 	at com.google.android.gms.internal.zzpu.run(Unknown Source)
06-08 09:41:56.510: E/AndroidRuntime(21462): 	at java.lang.Thread.run(Thread.java:856)
06-08 09:41:56.520: D/CocosPlayClient.cpp(21462): isEnabled = 0
06-08 09:41:56.520: D/CocosPlayClient.cpp(21462): isDemo = 0
06-08 09:41:56.520: D/CocosPlayClient.cpp(21462): isNotifyFileLoadedEnabled = 0
06-08 09:41:57.820: D/cocos2d-x debug info(21462): create rendererRecreatedListener for GLProgramState
06-08 09:41:57.840: D/cocos2d-x debug info(21462): cocos2d: fullPathForFilename: No file found at Marker Felt. Possible missing file.
06-08 09:41:57.870: D/cocos2d-x debug info(21462): create rendererRecreatedListener for GLProgramState
06-08 09:41:57.880: D/cocos2d-x debug info(21462): cocos2d: fullPathForFilename: No file found at Marker Felt. Possible missing file.
06-08 09:41:57.900: D/cocos2d-x debug info(21462): cocos2d: fullPathForFilename: No file found at Marker Felt. Possible missing file.
06-08 09:41:57.920: D/dalvikvm(21462): GC_CONCURRENT freed 298K, 7% free 13730K/14727K, paused 13ms+3ms, total 33ms
06-08 09:41:57.920: D/dalvikvm(21462): WAIT_FOR_CONCURRENT_GC blocked 11ms
06-08 09:41:57.930: D/cocos2d-x debug info(21462): cocos2d: fullPathForFilename: No file found at Marker Felt. Possible missing file.
06-08 09:41:57.940: D/cocos2d-x debug info(21462): cocos2d: fullPathForFilename: No file found at Marker Felt. Possible missing file.
06-08 09:41:57.960: D/cocos2d-x debug info(21462): cocos2d: fullPathForFilename: No file found at Marker Felt. Possible missing file.
06-08 09:41:58.010: D/dalvikvm(21462): GC_FOR_ALLOC freed 306K, 9% free 13628K/14855K, paused 35ms, total 35ms
06-08 09:41:58.020: D/cocos2d-x debug info(21462): cocos2d: fullPathForFilename: No file found at Marker Felt. Possible missing file.
06-08 09:41:58.030: D/cocos2d-x debug info(21462): cocos2d: fullPathForFilename: No file found at Marker Felt. Possible missing file.
06-08 09:41:58.050: D/cocos2d-x debug info(21462): cocos2d: fullPathForFilename: No file found at fonts/Marker Felt.ttf. Possible missing file.
06-08 09:41:58.060: D/cocos2d-x debug info(21462): cocos2d: fullPathForFilename: No file found at fonts/Marker Felt.ttf. Possible missing file.
06-08 09:41:58.080: W/PopupManager(21462): You have not specified a View to use as content view for popups. Falling back to the Activity content view. Note that this may not work as expected in multi-screen environments
06-08 09:41:58.180: D/cocos2d-x debug info(21462): cocos2d: fullPathForFilename: No file found at fonts/Marker Felt.ttf. Possible missing file.
06-08 09:41:58.200: D/cocos2d-x debug info(21462): cocos2d: fullPathForFilename: No file found at fonts/Marker Felt.ttf. Possible missing file.
06-08 09:41:58.270: D/dalvikvm(21462): GC_CONCURRENT freed 339K, 8% free 13673K/14855K, paused 14ms+2ms, total 41ms
06-08 09:41:59.120: I/Process(21462): Sending signal. PID: 21462 SIG: 9

~~~

**Comment by yinjimmy** [comment]
fixed with https://github.com/sdkbox/sdkbox-sample-sdkboxplay/commit/25d31fa505e95e3ec34174558598d18f6d441a24
